import win32con
WA_PLAYING = 'playing'
WA_PAUSED = 'paused'
WA_STOPPED = 'stopped'
WA_FULLPATH = r'C:\Program Files (x86)\Winamp\winamp.exe'
CALLER_HOTKEY = 'hotkey'
CALLER_HTTP = 'http'
CALLER_MENU = 'menu'
CALLER_SCHEDULER = 'scheduler'
CALLER_BROWSER = 'browser'
CALLER_LOAD = 'load'
CALLER_IDLE = 'idle'
CALLER_LEFT_CLICK = 'left_click'
CALLER_STARTUP = 'startup'
CALLER_SYS_STARTUP = 'sys_startup'
CALLER_EVENT = 'event'
CALLER_EXIT = 'exit'
CALLER_FILE_CHANGE = 'file_change'
TDCBF_OK_BUTTON = 1
TDCBF_YES_BUTTON = 2
TDCBF_NO_BUTTON = 4
TDCBF_CANCEL_BUTTON = 8
TDCBF_RETRY_BUTTON = 16
TDCBF_CLOSE_BUTTON = 32
TD_ICON_BLANK = 100
TD_ICON_WARNING = 101
TD_ICON_QUESTION = 102
TD_ICON_ERROR = 103
TD_ICON_INFORMATION = 104
TD_ICON_BLANK_AGAIN = 105
TD_ICON_SHIELD = 106
TDF_ENABLE_HYPERLINKS = 1
TDF_USE_HICON_MAIN = 2
TDF_USE_HICON_FOOTER = 4
TDF_ALLOW_DIALOG_CANCELLATION = 8
TDF_USE_COMMAND_LINKS = 16
TDF_USE_COMMAND_LINKS_NO_ICON = 32
TDF_EXPAND_FOOTER_AREA = 64
TDF_EXPANDED_BY_DEFAULT = 128
TDF_VERIFICATION_FLAG_CHECKED = 256
TDF_SHOW_PROGRESS_BAR = 512
TDF_SHOW_MARQUEE_PROGRESS_BAR = 1024
TDF_CALLBACK_TIMER = 2048
TDF_POSITION_RELATIVE_TO_WINDOW = 4096
TDF_RTL_LAYOUT = 8192
TDF_NO_DEFAULT_RADIO_BUTTON = 16384
TDF_CAN_BE_MINIMIZED = 32768
DL_CANCEL = win32con.IDCANCEL
DL_OK = win32con.IDOK
DL_TIMEOUT = 0
WINDOW_MINIMIZED = win32con.SW_SHOWMINNOACTIVE
WINDOW_MAXIMIZED = win32con.SW_SHOWMAXIMIZED
WINDOW_HIDDEN = win32con.SW_HIDE
DATE_FORMAT = '%A, %d %B %Y %H:%M:%S.%f'
DATE_STR_FILE = '%Y-%m-%d_%H-%M-%S'
RE_DATE_STR_FILE = r'\d\d\d\d-\d\d-\d\d_\d\d-\d\d_\d\d'
DATE_STR_FILE_SHORT = '%Y-%m-%d'
RE_DATE_STR_FILE_SHORT = r'\d\d\d\d-\d\d-\d\d'
DATE_STR_HUMAN = '%Y.%m.%d %H:%M:%S'
RE_DATE_STR_HUMAN = r'\d\d\d\d.\d\d.\d\d \d\d:\d\d:\d\d'
DATE_STR_HUMAN_SHORT = '%Y.%m.%d'
RE_DATE_STR_HUMAN_SHORT = r'\d\d\d\d.\d\d.\d\d'
_APP_FAVICON = 'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAktJREFUeNqUU0toE1EUPW+SNJlJrUlrqiFGaIOfmhSCoFVEodRaFxUEoQrizo0IXSi4LgXFVUEXLjQRPxt3IipSUGlFg0X7QzDG0jZqbBqTGGoy5p/xvqEJMW0VL3Nn5t13z5l775zHkv5TqDF3JCX167XFHlFbaOKBfElIlxQ2a6zLD2uYcpdCgXIyqyIwpHK625R0gtFCzumwkDRCKygwGTIwi1k1SeGXwgYYUwarCcRsQTNCX90zGbbg3lQbAjHzH2VtbkjhyNYgju6YRzDREPaMO7dcOfy6oFVZFXaVgx98cMAz7sJqFvpZr+69+mxDRJasibR+iML9vIJ2Kmt6Jm5iF54eBPWKtcyoy0OqKyAqi8vdYL9AtzMEYY8/tlbA1N8KsNsaxbXeUZpJqTI/XgEn6OGrqUWLGt0gpeE99gzO5ngF3O34goHON7jx1oUwDbbKujhBK80A1JMaif0S8TJow+VuH3bbIuhsCeFcxzSGfLswFtpUW5hFq86wJnpncicEauPigXdcAxgc6cDEQvOqc+EEs5TcZjJk8SNtKP9r3Jpw4lGgBbmiBksZ/VpzjfEWnvM318b4it2oLP0NzG2YE1zn6urdPg+G/7Ic+SVO4C+WhJt86sedM/9EORqX0CRl+Ov5J6cf+qul7CM1ul/M2XH//TZ8I+VVW6OYwSHHV5xsDyjfZWnMvj65r/Yw1RdKgpeE0scXiykjIilRPUxmAlvXyeUW8+Rnyb21BGXby9VJ2ugCU+zLsQSBP9FzlNxDPldO/i3AAPuE3dwUbVLNAAAAAElFTkSuQmCC'
MONITOR_ON = -1
MONITOR_OFF = 2
MONITOR_STANDBY = 1
MIME_TEXT = 'text/plain; charset=utf-8'
MIME_HTML = 'text/html; charset=utf-8'
MIME_BINARY = 'application/octet-stream'

if __name__ != '__main__':
	try:
		from .tools import patch_import
		patch_import()
	except ImportError:
		print('import of patch_import failed')
